FROM apache/airflow:3.2.2

USER root

RUN apt-get update && \
    apt-get install -y gcc g++ && \
    apt-get clean

USER airflow

COPY app/requirements.txt /requirements.txt

RUN pip install --no-cache-dir --upgrade pip

RUN pip install --no-cache-dir -r /requirements.txt